### ISSUE TITLE
Some issues on the Project (PART 1)

### ISSUE THREAD

**Issue by LionelZoc** [Mezatsong/ZeMovieQuiz#1]
## Backend 
- resolvers/user.ts 🛑 
 aucun control n'est fait dans ce resolver. c'est à dire que toute donnée d'utilisateur envoyée par le front essaie est enregistrée dans la base.  ce qui crée des erreurs lorsque j'essaie de register 2 fois la même personne avec le même mail.
 
- entities/User.ts 
 aucune unicité n'est porté sur le champs email 🛑 
 Le password est exposé en clair dans le retour d'api dur register 🛑 
- 
## Frontend
- le jeux 
j'ai systématiquement cette erreur lorsque je lance le jeux 
<img width="1020" alt="Capture d’écran 2022-07-28 à 19 26 31" src="https://user-images.githubusercontent.com/8299128/181601235-1d929784-ab23-4150-869a-ceecb88b6584.png">

Après quelques modifications j'ai cette erreur aussi 
<img width="831" alt="Capture d’écran 2022-07-28 à 19 51 33" src="https://user-images.githubusercontent.com/8299128/181604597-f46e226c-26fa-4ff1-98fe-89438676fa0d.png">

Je pense que le jeu bug un peu quand on lance le site avec une base vide (ou quand je lance puis je supprime la base et je relance). j'ai pu le fixer mais je te laisse debuger pour comprendre d'où vient le problème. 💪🏾 

## Retour 
j'ai un peu l'impression que la vidéo de ben  Awad n'a pas été suivie pour avoir des indices sur comment bien gérér au moins la partie 1 du test. 
La gestion des erreurs sur le login/register peut être améliorée. 
La [vidéo](https://www.youtube.com/watch?v=I6ypD7qv3Z8&t=16510s&ab_channel=BenAwad) donne vraiment des indices sur comment avoir une bonne app assez solide en terme de controls . essaie de la regarder pendant au moins 3h de temps ça devrait te permettre d'avoir une base fonctionnelle sur le projet ⏹️ 

pour l'instant je m'arrête là. je te laisse fixer ces retours le temps que j'analyse ton code sur la partie 2 (le jeu)

**Comment by Mezatsong** [comment]
Le password n'est pas exposé en clair dans le retour d'api dur register 
Quand on n'enregistre deux fois la meme personne avec le même mail, ça ne crée pas d'erreur
🛑 J'ai n'ai pas controlé l'unicité de l'email parce que l'enoncé n'a pas précisé, j'ai pensé à celà mais après je me suis dit que ce n'est qu'un test donc j'ai laissé. mais je me rend compte que c'était une erreur de laisser ainsi, je vais corriger.

![Register-password-is-hashed-on-line-17](https://user-images.githubusercontent.com/42788152/181718956-5dd0d099-8e12-42ad-835a-90ff8ca4999f.PNG)
![Register-password-is-not-in-clear](https://user-images.githubusercontent.com/42788152/181718961-80186a32-d631-41ec-a926-12c4abd25cf7.PNG)

**Comment by Mezatsong** [comment]
En ce qui concerne le jeu, j'ai l'impression que tu n'a pas rempli la clé d'api de moviedb dans le fichier .env.development car j'ai cette erreur quand la requête vers moviedb échoue. 

![image](https://user-images.githubusercontent.com/42788152/181720455-1e81a35a-cfb8-4daa-a4a9-55371e93b889.png)

**Comment by Mezatsong** [comment]
L'erreur *No repository found for Question*, je ne l'ai pas eu, j'aimerais donc avoir les étapes pour reproduire l'erreur stp

**Comment by LionelZoc** [comment]
> L'erreur _No repository found for Question_, je ne l'ai pas eu, j'aimerais donc avoir les étapes pour reproduire l'erreur stp

je n'ai pas pu la reproduire pour l'instant mais si j'y arrive je te dirais. mais tu peux la laisser de côté pour l'instant , cette erreur

**Comment by LionelZoc** [comment]
> En ce qui concerne le jeu, j'ai l'impression que tu n'a pas rempli la clé d'api de moviedb dans le fichier .env.development car j'ai cette erreur quand la requête vers moviedb échoue.
> 
> ![image](https://user-images.githubusercontent.com/42788152/181720455-1e81a35a-cfb8-4daa-a4a9-55371e93b889.png)

j'ai pourtant bien renseigné l'api key 
<img width="834" alt="Capture d’écran 2022-07-29 à 14 59 25" src="https://user-images.githubusercontent.com/8299128/181765874-d943edf0-53e0-4936-908b-38f5c4683535.png">

**Comment by LionelZoc** [comment]
> Le password n'est pas exposé en clair dans le retour d'api dur register Quand on n'enregistre deux fois la meme personne avec le même mail, ça ne crée pas d'erreur 🛑 J'ai n'ai pas controlé l'unicité de l'email parce que l'enoncé n'a pas précisé, j'ai pensé à celà mais après je me suis dit que ce n'est qu'un test donc j'ai laissé. mais je me rend compte que c'était une erreur de laisser ainsi, je vais corriger.
> 
> ![Register-password-is-hashed-on-line-17](https://user-images.githubusercontent.com/42788152/181718956-5dd0d099-8e12-42ad-835a-90ff8ca4999f.PNG) ![Register-password-is-not-in-clear](https://user-images.githubusercontent.com/42788152/181718961-80186a32-d631-41ec-a926-12c4abd25cf7.PNG)

pour ce problème, en effet le password n'est pas en clair. ce que je voulais dire c'est que le backend ne devrait pas retourner le password au frontend. c'est une faille de securité en fait. 

pour tes test tu peux utiliser https://studio.apollographql.com/sandbox/explorer et renseigner `http://localhost:4000/graphql` dans le champs sandbox 
<img width="1437" alt="Capture d’écran 2022-07-29 à 15 03 50" src="https://user-images.githubusercontent.com/8299128/181766368-485f6f4c-d8d5-4588-a861-25f030867a6e.png">

**Comment by Mezatsong** [comment]
> pour ce problème, en effet le password n'est pas en clair. ce que je voulais dire c'est que le backend ne devrait pas retourner >le password au frontend. c'est une faille de securité en fait.

D'accord, c'est vrai, un middle-man pourrait s'en servir

**Comment by Mezatsong** [comment]
**### Issue fixed**
